[workspace]
members = [
  "agama-cli",
  "agama-server",
  "agama-lib",
  "agama-locale-data",
]
resolver = "2"
exclude = [
  "migrate-wicked"
]

[workspace.package]
rust-version = "1.74"
edition = "2021"


