name: "migrate-wicked CI"

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust_ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./rust/agama-migrate-wicked

    strategy:
      fail-fast: false

    steps:
    - name: Git Checkout
      uses: actions/checkout@v3

    - name: Install toolchain
      run: rustup toolchain install stable

    - name: Install cargo-binstall
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-binstall

    - name: Install tarpaulin
      run: cargo-binstall --no-confirm cargo-tarpaulin

    - name: Unit tests
      run: cargo tarpaulin --color always -p agama-migrate-wicked --exclude-files "agama-locale-data/*" --exclude-files "agama-lib/*" --exclude-files "agama-settings/*" --exclude-files "agama-dbus-server/*" --exclude-files "agama-cli/*" --out xml

    - name: Lint tests
      run: cargo fmt --all -- --check

    - name: Cargo clippy
      run: cargo clippy -p agama-migrate-wicked -- --no-deps -D warnings

    - name: Cargo clippy on unit tests
      run: cargo clippy -p agama-migrate-wicked -- --no-deps --cfg test -A unused_imports -D warnings

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2
      with:
        base-path: ./rust
        format: cobertura
